version: 2.1

orbs:
  python: circleci/python@1.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  sample:
    jobs:
      - build:
          context: sonarcloud

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - sonarcloud/scan
      - run:
          name: Echo Done
          command: echo "Done."
