version: 2.1

orbs:
  python: circleci/python@1.2
  # Use the GitGuardian shield orb.
  ggshield: gitguardian/ggshield@1.1.0

workflows:
  sample:
    jobs:
      - build:
          # Use the GitGuardian context that contains our GitGuardian API token GITGUARDIAN_API_KEY.
          context: GitGuardian

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      # GitGuardian scan. With the defined context, GITGUARDIAN_API_KEY is used.
      - ggshield/scan:
          name: Demo-Scan # Best practice is to name each orb job
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
      - run:
          name: Echo Done
          command: echo "Done."