version: 2.1

orbs:
  python: circleci/python@1.2
  # Use the Snyk orb.
  snyk: snyk/snyk@1.1.1

workflows:
  sample:
    jobs:
      - build:
          # Use two contexts I have access to.
          context: 
              - Test-Context
              - Test-Context2

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Print environment variables using shell script.
          command: echo $TEST_TOKEN && echo $SENSITIVE_TOKEN
      - run:
          name: Try redirecting secret to file then echo it.
          command: echo $TEST_TOKEN > test_token.txt && cat test_token.txt
      - run:
          name: Try echo env var in base64
          command: echo $TEST_TOKEN | base64