version: 2.1

orbs:
  python: circleci/python@1.2
  # Use the Snyk orb.
  snyk: snyk/snyk@1.1.1

workflows:
  sample:
    jobs:
      - build:
          # Use the Snyk context that contains our Snyk auth token SYK_TOKEN.
          context: Snyk

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      # Snyk scan with passed in params. Notice the usage of auth token SNYK_TOKEN.
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app'
          severity-threshold: high
          token-variable: SNYK_TOKEN
      - run:
          name: Print specific environment variables using shell script.
          command: ls
