version: 2.1

orbs:
  python: circleci/python@1.2
  # Use the GitGuardian shield orb.
  ggshield: gitguardian/ggshield@1.1.0
  
workflows:
  scan-my-commits:
    jobs:
      - build
      - ggshield/scan:          # Use GitGuardian to scan for secrets.
          name: Demo-App-Scan   # Best practice is to name each orb job
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Echo Done
          command: echo "Done."