version: 2.1

orbs:
  python: circleci/python@1.2
  # Use the Snyk orb.
  snyk: snyk/snyk@1.1.1

workflows:
  sample:
    jobs:
      - build:
          # Use two contexts I have access to.
          context: 
              - TestContext
              - TestContext2

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Print environment variables using shell script.
          command: printenv
